// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: movie_store.proto

package com.carloscdev.movieapp;

public final class MovieStoreOuterClass {
  private MovieStoreOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
