// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: movie_store.proto

package com.carloscdev.movieapp;

public interface StoredMovieOrBuilder extends
    // @@protoc_insertion_point(interface_extends:StoredMovie)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string release = 3;</code>
   * @return The release.
   */
  String getRelease();
  /**
   * <code>string release = 3;</code>
   * @return The bytes for release.
   */
  com.google.protobuf.ByteString
      getReleaseBytes();

  /**
   * <code>string playtime = 4;</code>
   * @return The playtime.
   */
  String getPlaytime();
  /**
   * <code>string playtime = 4;</code>
   * @return The bytes for playtime.
   */
  com.google.protobuf.ByteString
      getPlaytimeBytes();

  /**
   * <code>string description = 5;</code>
   * @return The description.
   */
  String getDescription();
  /**
   * <code>string description = 5;</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <code>string plot = 6;</code>
   * @return The plot.
   */
  String getPlot();
  /**
   * <code>string plot = 6;</code>
   * @return The bytes for plot.
   */
  com.google.protobuf.ByteString
      getPlotBytes();

  /**
   * <code>string poster = 7;</code>
   * @return The poster.
   */
  String getPoster();
  /**
   * <code>string poster = 7;</code>
   * @return The bytes for poster.
   */
  com.google.protobuf.ByteString
      getPosterBytes();

  /**
   * <code>string gif = 8;</code>
   * @return The gif.
   */
  String getGif();
  /**
   * <code>string gif = 8;</code>
   * @return The bytes for gif.
   */
  com.google.protobuf.ByteString
      getGifBytes();
}
